
services:
  db-user-service:
    image: postgres:16
    restart: always
    env_file:
      - dbuser.env
    ports:
      - "5434:5432"
    volumes:
      - db_user_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_user_data: